[package]
name = "hollow"
version = "0.1.0"
edition = "2021"


[[bin]]
name = "hollow"
path = "src/bin/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colour = "0.7.0"
regex = "1.7.1"
